"""
(c) 2025 Stash AI Inc., All rights reserved.
Licensed under the [Plain Apache License](https://plainlicense.org/licenses/permissive/apache-2-0/).
"""

from mad_icon.utilities.icon_generation_utils import (
    check_masked_image_padding,
    cleanup_resources,
    determine_source_images,
    generate_html_tag,
    generate_manifest_entry,
    generate_output_files,
    get_masked_image_data,
    get_relative_path,
    has_value,
    load_icon_image,
    prepare_output_directories,
    process_icon_category,
    process_macos_clipped_icon,
    process_raster_icon,
    process_single_icon,
    process_svg_icon,
    read_source_from_arg,
    sequence_or_string_guard,
    setup_output_paths,
    validate_and_load_base_icon,
    validate_raster_image,
)
from mad_icon.utilities.image_processing import (
    analyze_svg_structure,
    check_masked_padding,
    create_macos_clipped_svg,
    desaturate_image,
    ensure_opaque_background,
    ensure_transparent_background,
    load_image,
    render_svg_to_png_bytes,
    resize_image,
)
from mad_icon.utilities.utilities import (
    data_path,
    is_none_type,
    load_file,
    make_dirs,
    parse_launch_options,
    retrieve_model,
)


__all__ = [
    "analyze_svg_structure",
    "check_masked_image_padding",
    "check_masked_padding",
    "cleanup_resources",
    "create_macos_clipped_svg",
    "data_path",
    "desaturate_image",
    "determine_source_images",
    "ensure_opaque_background",
    "ensure_transparent_background",
    "generate_html_tag",
    "generate_manifest_entry",
    "generate_output_files",
    "get_masked_image_data",
    "get_relative_path",
    "has_value",
    "has_value",
    "is_none_type",
    "load_file",
    "load_icon_image",
    "load_image",
    "make_dirs",
    "parse_launch_options",
    "prepare_output_directories",
    "process_icon_category",
    "process_macos_clipped_icon",
    "process_raster_icon",
    "process_single_icon",
    "process_svg_icon",
    "read_source_from_arg",
    "render_svg_to_png_bytes",
    "retrieve_model",
    "resize_image",
    "sequence_or_string_guard",
    "setup_output_paths",
    "validate_and_load_base_icon",
    "validate_raster_image",
]
